### ISSUE TITLE
Hello I have a question about your extended paper

### ISSUE THREAD

**Issue by Vision-sejin** [wpy1999/BAS-Extension#1]
First of all, I am very interested in your research and papers. Also, thank you for sharing these studies :)

So, I'm wondering. Is your extended paper under revision now?
Or.... Don't you have any plan about your extended paper? 
Then.. I'm so sad :( 

I want to know about your research results and the contents of your paper. 
I'm still waiting your official paper 

Thanks for reading and I'll be waiting for your answer.
Have a good day

**Comment by wpy1999** [comment]
Hello, thank you very much for your interest in our work. The extended version of BAS is still under review and needs to be revised. If the paper is accepted we will release the official paper as soon as possible.

**Comment by Vision-sejin** [comment]
> Hello, thank you very much for your interest in our work. The extended version of BAS is still under review and needs to be revised. If the paper is accepted we will release the official paper as soon as possible.

Hello now I'm trying to use your code. And I can train WSSS task but.. I can't inference.
To test the code, I need a resnet50.py in the net directory

So, could you share the resnet50.py for your test code? or Is it just vanilla resnet50 code?
Thank you :)

**Comment by wpy1999** [comment]
I am sorry for this omission, I have added resnet50.py in the net folder. Thank you for pointing this out!
