### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xixiaos** [wpy1999/BAS-Extension#2]
Hello author, may I ask if this sess/resnet50-19c8e357.pth file is not available Thank you!

**Comment by wpy1999** [comment]
I've added sess/resnet50-19c8e357.pth, you can download it from Google Drive (https://drive.google.com/drive/folders/1HkggF1NpbMnMBp14tmwZJOa5jaXemgSU) or Baidu Cloud Drive (https://pan.baidu.com/s/1krAEgKaEQO4geJeVMz8ZqQ?pwd=1999#list/path=%2F). Thanks for pointing out the omission!
