### ISSUE TITLE
About mobilenet with pre-training weights.

### ISSUE THREAD

**Issue by 893018991** [wpy1999/BAS-Extension#3]
Thank you for sharing this awesome code.
I would like to ask, can you provide a pre-training weight file about MobileNet v1?
Because I can't find the pre-trained weight file you use in your code（WSOL/Model/mobilenet.py） on the web.

**Comment by wpy1999** [comment]
Hi, you can download the pre-training weight from https://drive.google.com/file/d/1fEE763oyBIvdZaNS4HJVx4G_YAni9zZ2/view?usp=sharing

**Comment by 893018991** [comment]
OK.   Thank you very much for your help.
