### ISSUE TITLE
About customized dataset

### ISSUE THREAD

**Issue by EdQinHUST** [wpy1999/BAS-Extension#6]
Thanks for sharing your wonderful work！
I wonder if I use 我自己的数据集 in task WSSS with voc datasets，how to generate cls_label.npy documents?
如果是直接用make_cls_labels.py里面的代码，怎么考虑划分train.txt和text.txt的balance?
I'll appreciate it if there is an early reply.

**Comment by wpy1999** [comment]
感谢您对该工作的关注。我们的数据读取代码沿用了IRN的代码，cls_label.npy也是使用了之前工作提供的文件。很抱歉我不太清楚怎么构建一个新的cls_label.npy，或许您可以使用源代码中的cls_label.npy的读取代码，输出cls_label.npy里的文件信息和格式，然后根据自己的数据集重新修改里面的内容，最后再保存为npy格式。划分train.txt和text.txt

**Comment by wpy1999** [comment]
感谢您对该工作的关注。我们的数据读取代码沿用了IRN的代码，cls_label.npy也是使用了之前工作提供的文件。很抱歉我不太清楚怎么构建一个新的cls_label.npy，或许您可以使用源代码中的cls_label.npy的读取代码，输出cls_label.npy里的文件信息和格式，然后根据自己的数据集重新修改里面的内容，最后再保存为npy格式。  train.txt和text.txt的balance，您是指训练集和测试集样本个数以及每个类别个数的平衡吗，您可以使用相同比例的【训练集样本数：验证集集样本数】划分不同类别，您可以参考其他数据集的规模和他们的比例选择，例如PASCAL VOC原比例是1,464：1,456，后续的工作将其增强为12,046：1,456，COCO是82,081：40,137。我个人觉得，对于小数据集，常见的分类数据集(CUB)和语义分割任务似乎通常采用1：1的比例，但对于弱监督语义分割来说，这个比例恐怕难以训练，这也是为什么VOC用于弱监督语义分割时，大家都使用增强了的训练集。您构建数据集时可以参考VOC增强版的12,046：1,456比例。
